In [2]:
import numpy as np

In [15]:
v1 = np.array([10,20,5])
v2 = np.array([5,5,10])
print(v1.dot(v2))
print(v2+v1)
print(v1.ndim)
print(v1.shape)

200
[15 25 15]
1
(3,)


In [13]:
class Student():
    def __init__(self,name):
        self.name = name
    @property        
    def get_info(self):
        return f"My Name is {self.name}"
    

In [14]:
s1 = Student("George")
s1.get_info

'My Name is George'

In [4]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1)
print("================")
m2 = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
print(m2)
print("===============================")
print("==========Operations===========")

print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
==========Operations===========
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [23]:
m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(m1.ndim)
print(m1.shape)


2
(3, 3)


In [ ]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
print(mat)


[[1 2]
 [3 4]
 [5 6]]


In [38]:
mat.shape[1]

2

In [52]:
vec = np.array([1,
                2,
                3,
                4])
vec.shape[0]

4

In [43]:
vec = np.array([1,2,3,4])
mat = vec.reshape(vec.shape[0],1)
mat


array([[1],
       [2],
       [3],
       [4]])

In [45]:
vec = np.array([1,2,3,4])
mat = vec [:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [49]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mat.dtype

dtype('int64')